project:
  type: website
  output-dir: docs

website:
  title: "Michał Pawłowski"
  twitter-card: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/misza222
      - icon: twitter
        href: https://twitter.com/misza222
      - icon: linkedin
        href: https://linkedin.com/in/misza/
  open-graph: true

format:
  html:
    theme: litera
    css: styles.css
    link-external-newwindow: true
    # link-external-filter: '^(?:http:|https:)\/\/blog\.mpawlowski\.eu\/**'

comments: 
  utterances: 
    repo:  misza222/misza222.github.com